import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

describe("standalone product", () => {
  it("does not depend on WechatOnCloud paths", () => {
    const compose = readFileSync(resolve(root, "docker-compose.yml"), "utf8");
    assert.doesNotMatch(compose, /\.\.\/wechat/);
    assert.doesNotMatch(compose, /woc-panel|woc-wx/);
    assert.match(compose, /build: \.\/docker/);
    assert.match(compose, /image:\s*ghcr\.io\/jingxuankang\/gpt-pro-cloud-desktop:latest/);
    assert.match(compose, /image:\s*ghcr\.io\/jingxuankang\/gpt-pro-cloud-gateway:latest/);
    assert.doesNotMatch(compose, /gpt-pro-cloud-desktop:local|gpt-pro-cloud-gateway:local/);
    assert.match(compose, /\.\/data\/a:\/config/);
    assert.match(compose, /\.\/data\/b:\/config/);
    assert.match(compose, /START_URL: \$\{START_URL:-https:\/\/chatgpt\.com\}/);
    assert.match(compose, /PROXY_URL_OVERRIDE: \$\{PROXY_URL_A:-\}/);
    const proxyInit = readFileSync(resolve(root, "docker/proxy-init.sh"), "utf8");
    assert.match(proxyInit, /PROXY_URL_OVERRIDE/);
    assert.ok(proxyInit.includes('RAW="${RAW//\\[::1\\]/host.docker.internal}"'));
    assert.equal(proxyInit.includes('RAW="${RAW//[::1]/host.docker.internal}"'), false);
    assert.doesNotMatch(compose, /9222|9223/);
    assert.doesNotMatch(compose, /ports:[\s\S]*debug/i);
    const up = readFileSync(resolve(root, "scripts/up.sh"), "utf8");
    assert.match(up, /docker compose pull/);
    assert.match(up, /docker compose up -d/);
    const happyPath = up.split("if ! docker compose pull")[0];
    assert.doesNotMatch(happyPath, /--build/);
    assert.match(up, /docker compose up -d --build/);
    assert.match(up, /ghcr\.io\/jingxuankang\/gpt-pro-cloud-gateway:latest/);
    assert.match(up, /ghcr\.io\/jingxuankang\/gpt-pro-cloud-desktop:latest/);
    for (const name of ["README.md", "README.zh-CN.md", "Deploy.md"]) {
      const doc = readFileSync(resolve(root, name), "utf8");
      assert.match(doc, /ghcr\.io\/jingxuankang\/gpt-pro-cloud-gateway:latest/);
      assert.match(doc, /docker compose pull/);
      assert.doesNotMatch(doc, /docker login/);
    }
  });

  it("proxy-init.sh rewrites [::1] without eating colons or digits", () => {
    const src = readFileSync(resolve(root, "docker/proxy-init.sh"), "utf8");
    const rewrites = src
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l.startsWith('RAW="${RAW//'));
    assert.equal(rewrites.length, 3);
    const run = (url) => {
      const script = ["RAW=$(cat)", ...rewrites, 'printf %s "$RAW"'].join("\n");
      return execFileSync("bash", ["-c", script], { encoding: "utf8", input: url });
    };
    assert.equal(run("http://127.0.0.1:7890"), "http://host.docker.internal:7890");
    assert.equal(run("socks5://warp:1080"), "socks5://warp:1080");
    assert.equal(run("http://[::1]:7890"), "http://host.docker.internal:7890");
    assert.equal(run("socks5://localhost:7891"), "socks5://host.docker.internal:7891");
  });

  it("desktop opens ChatGPT and honors rewritten proxy", () => {
    const start = readFileSync(resolve(root, "docker/autostart"), "utf8");
    const init = readFileSync(resolve(root, "docker/proxy-init.sh"), "utf8");
    assert.match(start, /--app="\$\{START_URL\}"/);
    const launch = start.slice(start.indexOf("/usr/bin/chromium"));
    assert.doesNotMatch(launch, /--kiosk/);
    assert.match(start, /No --kiosk/);
    assert.match(start, /X <= -1000/);
    assert.match(start, /--start-fullscreen/);
    assert.match(start, /--user-data-dir=\/config\/chromium/);
    assert.doesNotMatch(start, /user-data-dir=\/config\/chromium-/);
    assert.match(start, /--test-type/);
    assert.match(start, /--proxy-server=/);
    assert.match(start, /gpc-proxy-override/);
    assert.match(start, /ENABLE_CDP/);
    assert.match(start, /TAB_SEATS/);
    assert.match(start, /\.gpc-cdp/);
    assert.match(start, /CDP_ON/);
    assert.match(start, /\$\{CDP_FLAGS\}/);
    assert.match(start, /remote-debugging-port=9222/);
    assert.match(start, /remote-debugging-address=127.0.0.1/);
    assert.doesNotMatch(start, /remote-debugging-address=0.0.0.0/);
    assert.doesNotMatch(start, /^\s*--remote-debugging-port=9222/m);
    assert.doesNotMatch(start, /^python3 \/usr\/local\/bin\/gpc-cdp-fwd/m);
    assert.match(start, /sync_cdp_fwd/);
    assert.match(start, /gpc-cdp-fwd/);
    assert.match(start, /file-pipe/);
    assert.match(start, /file-pipe still on/);
    const fwd = readFileSync(resolve(root, "docker/cdp-fwd.py"), "utf8");
    assert.match(fwd, /ALLOWED_NAMES/);
    assert.match(fwd, /gpt-pro-cloud-gateway/);
    assert.match(init, /host\.docker\.internal/);
    const wm = readFileSync(resolve(root, "docker/update-autostart.sh"), "utf8");
    assert.match(wm, /gpc-no-chrome/);
    assert.match(wm, /<decor>no<\/decor>/);
    assert.match(wm, /<fullscreen>yes<\/fullscreen>/);
  });

  it("gateway is the only entry", () => {
    const gw = readFileSync(resolve(root, "gateway/server.mjs"), "utf8");
    assert.match(gw, /\/healthz/);
    assert.match(gw, /\/login/);
    assert.match(gw, /parseInstances/);
    assert.match(gw, /\/api\/login/);
    assert.match(gw, /\/api\/admin\/users/);
    const hide = readFileSync(resolve(root, "docker/hide-kasm.sh"), "utf8");
    assert.match(hide, /noVNC_logo/);
    assert.match(hide, /noVNC_transition/);
    const ui = readFileSync(resolve(root, "gateway/web/app.js"), "utf8");
    assert.match(ui, /\/vnc\/index\.html/);
    assert.match(ui, /seat-cast/);
    assert.match(ui, /\/seats\//);
    assert.match(ui, /deskMode/);
    assert.match(gw, /createSeatRegistry/);
    assert.match(gw, /startSeatScreencast/);
    assert.match(gw, /TAB_SEATS_MAX/);
    assert.match(gw, /createParkedChatGPTTab/);
    assert.match(gw, /claimedTargetIds/);
    assert.doesNotMatch(gw, /probeDeskSession/);
    assert.doesNotMatch(gw, /withDeskCdp\(id, \(\) => createParkedChatGPTTab/);
    assert.doesNotMatch(gw, /withDeskCdp\(id, \(\) => runOnboard/);
    assert.match(gw, /forgetDeskBrowser/);
    assert.match(gw, /withDeskCdp/);
    assert.match(gw, /ONBOARD_YIELD_MS/);
    assert.match(gw, /deskCdpOn/);
    assert.match(gw, /applyDeskCdpLive/);
    assert.match(gw, /setDeskCdp/);
    assert.match(gw, /这个号未开多人分屏/);
    assert.match(gw, /页面协助需要开启调试口/);
    assert.match(ui, /clipboard_up=true/);
    assert.match(ui, /\/api\/desks\/\$\{id\}\/paste/);
    assert.match(ui, /\/api\/presence\/leave/);
    assert.match(ui, /noVNC_keyboardinput/);
    assert.match(ui, /clip-keys/);
    assert.match(ui, /\$\{MOD\}\+V/);
    assert.match(ui, /\/api\/desks\/\$\{id\}\/copy/);
    assert.match(ui, /\/api\/desks\/\$\{state\.deskId\}\/share/);
    assert.match(ui, /\/api\/desks\/\$\{id\}\/onboard/);
    assert.doesNotMatch(ui, /new-project|project-modal|新项目/);
    assert.match(gw, /grabDeskClipboard/);
    assert.match(gw, /PAGE_CLIP_READ/);
    assert.match(gw, /isDeskOutboundFilePath/);
    assert.match(gw, /keepDeskDownloadsInside/);
    assert.doesNotMatch(gw, /18790\/grab/);
    assert.match(gw, /SHARE_CLICK/);
    assert.match(gw, /projectOnboardScript/);
    assert.match(gw, /waitForDesk/);
    assert.match(gw, /kickOnboard/);
    assert.match(gw, /lockSeatToProject/);
    assert.match(gw, /pickNamedProjectHref/);
    assert.match(gw, /listSeatProjectLinks/);
    assert.match(gw, /navigateSeatToUrl/);
    assert.doesNotMatch(gw, /const create = !users\.readyOn/);
    assert.match(gw, /deskCdpOn/);
    assert.match(gw, /\/api\/admin\/settings/);
    assert.match(gw, /多人分屏暂未开放/);
    assert.doesNotMatch(ui, /data-cdp-toggle/);
    assert.doesNotMatch(ui, /<b>多人分屏<\/b>/);
    assert.doesNotMatch(ui, /暂未开放/);
    assert.doesNotMatch(ui, /data-cdp-master/);
    assert.doesNotMatch(ui, /cdpMasterState/);
    assert.doesNotMatch(ui, /indeterminate/);
    assert.doesNotMatch(ui, /允许多人同时使用/);
    assert.doesNotMatch(ui, /开启调试口/);
    assert.doesNotMatch(ui, /id="assist-toggle"/);
    assert.doesNotMatch(ui, /body: \{ assist:/);
    assert.match(gw, /readyOn/);
    assert.doesNotMatch(ui, /chromium 未就绪/);
    assert.match(gw, /projectDesk/);
    assert.match(gw, /\/onboard/);
    assert.match(gw, /18790/);
    assert.match(gw, /createLoginLimiter/);
    assert.match(gw, /createSessionStore/);
    assert.match(gw, /sessions\.json/);
    assert.match(gw, /content-security-policy/);
    assert.match(gw, /429/);
    assert.match(gw, /"PATCH"/);
    assert.match(gw, /deleteByUser/);
    assert.match(gw, /\/kick/);
    assert.match(gw, /kickLiveSession/);
    assert.match(gw, /createSocketHub/);
    assert.match(ui, /data-manage/);
    assert.match(ui, /"PATCH"/);
    assert.match(gw, /\/api\\\/admin\\\/desks/);
    assert.match(gw, /renameDesk/);
    assert.match(gw, /provisionDesk/);
    assert.match(gw, /retireDesk/);
    assert.match(gw, /removeDeskContainer/);
    assert.match(gw, /ensureDeskContainer/);
    assert.match(gw, /reconcileExtraDesks/);
    assert.match(ui, /data-rename/);
    assert.match(ui, /data-add-desk/);
    assert.match(ui, /data-delete/);
    assert.match(ui, /确定删除/);
    assert.match(ui, /\/api\/admin\/desks/);
    assert.match(ui, /正在启动/);
    const compose = readFileSync(resolve(root, "docker-compose.yml"), "utf8");
    assert.match(compose, /\/var\/run\/docker\.sock:\/var\/run\/docker\.sock/);
    assert.match(compose, /DESKTOP_TEMPLATE=gpt-pro-cloud-a/);
    assert.match(compose, /desktop-a/);
    assert.match(compose, /desktop-b/);
    assert.match(gw, /\/api\/setup/);
    assert.match(gw, /hasAdmin/);
    assert.match(ui, /创建管理员/);
    assert.match(gw, /setDeskProxy/);
    assert.match(gw, /setAllDeskProxies/);
    assert.match(gw, /applyDeskProxiesLive/);
    assert.match(gw, /\/api\/admin\/proxies/);
    assert.match(ui, /#\/settings/);
    assert.match(ui, /data-proxy-save/);
    assert.match(ui, /data-proxy-pick/);
    assert.match(ui, /id="proxy-all"/);
    assert.match(ui, /全部应用/);
    assert.match(gw, /setSettings/);
    assert.match(ui, /data-fps/);
    assert.match(ui, /fps-pick/);
    assert.match(ui, /deskVncFrameRate/);
    assert.match(ui, /framerate=\$\{fps\}/);
    assert.match(ui, /framerate_image_mode/);
    assert.match(ui, /framerate_streaming_mode/);
    assert.match(ui, /applyVncFrameRate/);
    assert.match(ui, /updateConnectionSettings/);
    assert.match(ui, /桌面画质/);
    assert.match(ui, /data-assign/);
    assert.match(ui, /data-resetpw/);
    assert.match(ui, /data-toggle/);
    assert.match(ui, /断开/);
    assert.doesNotMatch(ui, /踢出去/);
    assert.match(ui, /data-kick-desk/);
    assert.match(ui, /occupancy/);
    assert.match(ui, /\/api\/admin\/users\/\$\{v\.id\}\/kick/);
    assert.doesNotMatch(ui, /cdp-empty/);
    assert.doesNotMatch(ui, /每个账号单独开/);
    assert.match(ui, /复制粘贴/);
    assert.doesNotMatch(ui, /到管理添加/);
    assert.doesNotMatch(ui, /短暂断开当前画面/);
    assert.doesNotMatch(ui, /data-cdp-toggle/);
    assert.doesNotMatch(ui, /data-cdp-master|cdp-master|cdpMasterState/);
    assert.doesNotMatch(ui, /开启后一并提供/);
    assert.doesNotMatch(ui, /项目页锁定/);
    assert.doesNotMatch(ui, /页面体验锁定/);
    assert.doesNotMatch(ui, /第一人看整桌/);
    assert.doesNotMatch(ui, /调试口/);
    assert.doesNotMatch(ui, /cdp-points|cdp-lead|cdp-label/);
    assert.doesNotMatch(ui, /每人独立标签|顶栏可以一键分享|记忆互不影响/);
    assert.doesNotMatch(ui, /无法检测|检测不到|undetectable/i);
    assert.doesNotMatch(ui, /老板号/);
    assert.doesNotMatch(ui, /互不可见/);
    assert.doesNotMatch(ui, /顶栏格子/);
    const settingsStart = ui.indexOf("function renderSettings");
    const settingsBlock = ui.slice(settingsStart, ui.indexOf("const isMac", settingsStart));
    assert.doesNotMatch(settingsBlock, /data-cdp-toggle|cdp-rows|cdp-empty/);
    assert.doesNotMatch(settingsBlock, /多人分屏|暂未开放/);
    assert.match(settingsBlock, /<b>复制粘贴<\/b>/);
    assert.match(settingsBlock, /<b>出口代理<\/b>/);
    assert.doesNotMatch(settingsBlock, /data-cdp-toggle|checkbox|switch-row/);
    assert.doesNotMatch(settingsBlock, /data-cdp-master|cdp-master/);
    assert.doesNotMatch(settingsBlock, /assist-note/);
    assert.doesNotMatch(settingsBlock, /每个账号单独开|class="cdp-rows"/);
    const css = readFileSync(resolve(root, "gateway/web/app.css"), "utf8");
    assert.match(css, /\.fps-pick/);
    assert.match(css, /\.fps-row/);
    const panelHead = css.slice(css.indexOf(".panel-head {"), css.indexOf(".panel-head b"));
    assert.match(panelHead, /padding:\s*1[89]px\s+20px\s*;/);
    assert.doesNotMatch(panelHead, /padding:\s*18px\s+20px\s+4px/);
    assert.match(panelHead, /justify-content:\s*center/);
    assert.match(css, /\.cardgrid/);
    assert.match(css, /\.sec-head/);
    assert.match(css, /\.chip\.live/);
    assert.match(css, /\.status\.live/);
    assert.match(css, /\.acts/);
    assert.match(css, /\.cdp-empty/);
    assert.doesNotMatch(css, /\.cdp-master|\.cdp-points|\.cdp-lead|\.assist-note|:indeterminate/);
    assert.match(css, /\.seat-cast/);
    assert.doesNotMatch(css, /\.clip-note/);
    const zhReadme = readFileSync(resolve(root, "README.zh-CN.md"), "utf8");
    assert.doesNotMatch(zhReadme, /老板号/);
    assert.doesNotMatch(zhReadme, /互不可见/);
    assert.doesNotMatch(zhReadme, /顶栏格子/);
    const clipd = readFileSync(resolve(root, "docker/clipd.py"), "utf8");
    assert.match(clipd, /xclip/);
    assert.match(clipd, /image\//);
    assert.match(clipd, /_looks_like_image/);
    assert.match(clipd, /do not throw away a PNG/);
    assert.match(clipd, /not targets.strip/);
    const noLeak = readFileSync(resolve(root, "docker/no-file-leak.sh"), "utf8");
    assert.match(noLeak, /www\/Downloads/);
    assert.match(noLeak, /gpc-downloads/);
    assert.match(noLeak, /DefaultDownloadDirectory/);
    const deskDf = readFileSync(resolve(root, "docker/Dockerfile"), "utf8");
    assert.match(deskDf, /04-no-file-leak/);
    const auto = readFileSync(resolve(root, "docker/autostart"), "utf8");
    assert.match(auto, /download-default-directory=\/config\/gpc-downloads/);
    assert.match(auto, /XDG_DOWNLOAD_DIR=\/config\/gpc-downloads/);
    assert.match(ui, /writeCopyFetchToLocal/);
    assert.match(ui, /copyFromDesk\(true\)/);
    assert.match(ui, /image\/png/);
    assert.match(clipd, /\/proxy/);
    assert.match(clipd, /gpc-proxy-override/);
    assert.match(clipd, /\/cdp/);
    assert.match(clipd, /gpc-cdp/);
    assert.match(clipd, /kill_chromium/);
    assert.match(clipd, /CHROMIUM_KILL_PATTERNS/);
    assert.match(clipd, /\/usr\/lib\/chromium\/chromium/);
    assert.match(clipd, /user-data-dir=\/config\/chromium/);
    assert.doesNotMatch(clipd, /pkill.*\/usr\/bin\/chromium/);
    const chrome = readFileSync(resolve(root, "lib/chrome.mjs"), "utf8");
    assert.match(chrome, /waitForDesk/);
    assert.match(chrome, /TAB_CLIP_READ/);
    assert.match(chrome, /PAGE_CLIP_READ/);
    assert.match(chrome, /grabDeskClipboard/);
    assert.match(chrome, /preferCopiedClip/);
    assert.match(chrome, /18790\/grab/);
    assert.match(chrome, /evaluateOnTarget/);
    assert.doesNotMatch(chrome, /webSocketDebuggerUrl/);
    const cdp = readFileSync(resolve(root, "lib/cdp.mjs"), "utf8");
    assert.match(cdp, /sessionFromProbe/);
    assert.match(cdp, /listDeskCookies/);
    assert.match(cdp, /probeDeskSession/);
    assert.match(cdp, /deskBrowserWs/);
    assert.match(cdp, /createDeskBrowserPool/);
    assert.match(cdp, /forgetDeskBrowser/);
    assert.match(cdp, /Target.getTargets/);
    assert.match(cdp, /createTargetViaHttp/);
    assert.match(cdp, /json\/new/);
    assert.match(cdp, /newWindow: false/);
    assert.match(cdp, /background: true/);
    assert.match(cdp, /pickUnclaimedChatGPTTarget/);
    assert.doesNotMatch(cdp, /newWindow: true/);
    const fwd = readFileSync(resolve(root, "docker/cdp-fwd.py"), "utf8");
    assert.match(fwd, /PUT /);
    assert.match(fwd, /force_connection_close/);
    assert.match(fwd, /is_ws_upgrade/);
    assert.match(fwd, /close_pair/);
    assert.match(fwd, /select\.select/);
    const seats = readFileSync(resolve(root, "lib/seats.mjs"), "utf8");
    assert.match(seats, /DEFAULT_TAB_SEAT_CAP/);
    assert.match(seats, /targetsVisibleToSeat/);
    assert.match(seats, /该账号正在使用中/);
    assert.doesNotMatch(seats, /有人在使用/);
    assert.doesNotMatch(seats, /请管理员开启/);
    const gwPkg = readFileSync(resolve(root, "gateway/package.json"), "utf8");
    assert.match(gwPkg, /"ws"/);
    const readme = readFileSync(resolve(root, "README.md"), "utf8");
    assert.match(readme, /TAB_SEATS_MAX/);
    assert.match(readme, /Page.startScreencast/);
    assert.match(readme, /opt-in/i);
    assert.match(readme, /off by default/i);
    assert.match(readme, /ClipboardEvent/);
    assert.doesNotMatch(readme, /Images are not pasted on tab seats/);
    assert.match(readme, /every occupant including the first/);
    assert.doesNotMatch(readme, /second Chrome|second Docker|user-data-dir-\/config\/chromium-/i);
    const zh = readFileSync(resolve(root, "README.zh-CN.md"), "utf8");
    assert.match(zh, /默认关闭/);
    assert.match(zh, /调试口|CDP/);
    assert.match(zh, /每人都是独立标签/);
    assert.match(zh, /第一人看整桌/);
    const tabPaste = readFileSync(resolve(root, "lib/tab-paste.mjs"), "utf8");
    assert.match(tabPaste, /ClipboardEvent/);
    assert.match(tabPaste, /document\.activeElement/);
    assert.match(tabPaste, /TAB_PASTE_NEED_FOCUS/);
    assert.doesNotMatch(tabPaste, /18790|xclip/);
    assert.doesNotMatch(tabPaste, /querySelector|prosemirror|prompt-textarea/i);
    assert.match(gw, /tabPastePlan/);
    assert.match(gw, /desktop-\$\{id\}:18790/);
    assert.match(ui, /点一下输入框再粘贴/);
    assert.match(ui, /id="upload-files"/);
    assert.match(ui, /id="os-files"/);
    assert.match(ui, /type="file"/);
    assert.match(ui, /onRemoteFileChooser/);
    assert.match(ui, /\/api\/desks\/\$\{id\}\/files/);
    assert.match(ui, /file-drop-shield/);
    assert.match(ui, /startChooserPoll/);
    assert.doesNotMatch(ui, /console\.(log|info|debug)\([^)]*data/);
    assert.match(gw, /handleDeskFileUpload/);
    assert.match(gw, /applyDeskUpload/);
    assert.match(gw, /watchExclusiveFileChooser/);
    assert.match(gw, /ensureExclusiveFilePipe/);
    assert.match(gw, /stageDeskUpload/);
    assert.doesNotMatch(gw, /watchAdminFileChooser|FILE_CDP_OFF|未开多人分屏时无法上传/);
    const chooser = readFileSync(resolve(root, "lib/file-chooser.mjs"), "utf8");
    assert.match(chooser, /Page.setInterceptFileChooserDialog/);
    assert.match(chooser, /Page.fileChooserOpened/);
    assert.match(chooser, /DOM.setFileInputFiles/);
    assert.match(chooser, /Browser.setDownloadBehavior/);
    assert.match(chooser, /gpc-downloads/);
    assert.match(chooser, /文件太大，请选择 12MB 以内的文件/);
    assert.match(chooser, /Exclusive VNC/);
    assert.doesNotMatch(chooser, /console\.(log|info|debug)/);
    assert.doesNotMatch(chooser, /请管理员开启多人分屏/);
    assert.match(chooser, /Browser\.downloadWillBegin/);
    assert.match(chooser, /Browser\.downloadProgress/);
    assert.match(chooser, /eventsEnabled: true/);
    assert.match(chooser, /sanitizeDownloadName/);
    assert.match(chooser, /armChooserEvidence/);
    assert.match(chooser, /waitForChooserEvidence/);
    assert.match(chooser, /FILE_NOT_ADDED/);
    assert.match(ui, /id="download-file"/);
    assert.match(ui, /startDownloadPoll/);
    assert.match(ui, /grabDeskDownload/);
    assert.match(ui, /downloads\/pull/);
    assert.match(gw, /watchDeskDownloads/);
    assert.match(gw, /handleDeskFileDownload/);
    assert.match(gw, /resolveDeskDownload/);
    assert.match(gw, /getArchive/);
    assert.match(gw, /content-disposition/);
    assert.doesNotMatch(ui, /console\.(log|info|debug)/);
    const sweep = readFileSync(resolve(root, "lib/sweep.mjs"), "utf8");
    assert.match(sweep, /SWEEP_HOUR = 3/);
    assert.match(sweep, /gpc-up-\*/);
    assert.match(sweep, /find \$\{DESK_DOWNLOAD_DIR\}/);
    assert.match(sweep, /wc -l/);
    assert.match(gw, /createNightlySweeper/);
    assert.match(gw, /execCapture/);
    assert.match(readFileSync(resolve(root, "package.json"), "utf8"), /sweep\.test\.mjs/);
    assert.match(readFileSync(resolve(root, "lib/file-chooser.mjs"), "utf8"), /UPLOAD_KEEP_MS = 60 \* 60 \* 1000/);
    assert.match(readFileSync(resolve(root, "package.json"), "utf8"), /file-chooser\.test\.mjs/);
    assert.match(readFileSync(resolve(root, "package.json"), "utf8"), /desk-clipboard\.test\.mjs/);
    assert.doesNotMatch(ui, /分屏席位暂不支持粘贴图片/);
    assert.doesNotMatch(ui, /图片粘贴暂不可用/);
    assert.match(chrome, /projectOnboardScript/);
    assert.match(chrome, /allowCreate/);
    assert.match(chrome, /inCreateForm/);
    assert.match(chrome, /New project/);
    assert.match(chrome, /project-only memory/);
    assert.match(chrome, /open project home/i);
    assert.match(chrome, /项目没有出现/);
    assert.match(chrome, /projectHref/);
    assert.match(chrome, /g-p-/);
    assert.match(chrome, /READ_PROJECT_URL/);
    assert.match(chrome, /LIST_PROJECT_LINKS/);
    assert.match(chrome, /listSeatProjectLinks/);
    assert.match(chrome, /isConnected/);
    assert.doesNotMatch(chrome, /if \(!visible\(el\) \|\| inCreateForm/);
    assert.doesNotMatch(
      chrome.slice(chrome.indexOf("LIST_PROJECT_LINKS"), chrome.indexOf("projectOnboardScript")),
      /getClientRects/,
    );
    const jail = readFileSync(resolve(root, "lib/project-jail.mjs"), "utf8");
    assert.match(jail, /bounceUrl/);
    assert.match(jail, /isAllowedJailUrl/);
    assert.match(jail, /shouldEnforceJailReplace/);
    assert.match(jail, /shouldApplyProjectHideMark/);
    assert.match(jail, /projectRowForControl/);
    assert.match(jail, /projectJailHideCss/);
    assert.match(jail, /projectJailProbeExpression/);
    assert.match(jail, /applyJailCssViaCdp/);
    assert.match(jail, /shouldReuseSeatJail/);
    assert.match(jail, /shouldHideOtherProject/);
    assert.match(jail, /shouldBlockProjectClick/);
    assert.match(jail, /seatStartUrl/);
    assert.match(jail, /projectJailScript/);
    assert.match(jail, /addScriptToEvaluateOnNewDocument/);
    assert.match(jail, /Page\.navigate/);
    assert.match(jail, /auth\.openai\.com/);
    assert.match(jail, /g-p-/);
    assert.match(jail, /isBlockedJailChord/);
    assert.match(jail, /isCopyOrPasteChord/);
    assert.match(jail, /shouldForwardSeatKey/);
    assert.match(jail, /setWindowOpenHandler/);
    assert.match(jail, /Target\.closeTarget/);
    assert.match(jail, /jailHotkeyScript/);
    assert.match(jail, /slugifyProjectName/);
    assert.match(jail, /pickNamedProjectHref/);
    assert.match(jail, /navigateSeatToUrl/);
    assert.doesNotMatch(jail, /completely impossible/i);
    assert.match(gw, /createSeatJailRegistry/);
    assert.match(gw, /seatStartUrl/);
    assert.match(gw, /armSeatProjectJail/);
    assert.match(gw, /projectUrlOn/);
    assert.match(gw, /startUrl/);
    assert.match(gw, /seatStartUrl\(\{ cdp, projectUrl \}\)/);
    const userStore = readFileSync(resolve(root, "lib/users.mjs"), "utf8");
    assert.match(userStore, /projectUrls/);
    assert.match(userStore, /projectUrlOn/);
    assert.match(userStore, /vncFrameRate/);
    assert.match(userStore, /VNC_FRAME_RATES/);
    assert.match(userStore, /帧率只能是 15 \/ 24 \/ 30 \/ 60/);
    const deskCdpOnFn = userStore.slice(userStore.indexOf("deskCdpOn("), userStore.indexOf("setDeskCdp"));
    assert.match(deskCdpOnFn, /return false/);
    assert.doesNotMatch(deskCdpOnFn, /data\.deskCdp/);
    const screencast = readFileSync(resolve(root, "lib/screencast.mjs"), "utf8");
    assert.match(screencast, /armSeatJail/);
    assert.match(screencast, /projectUrl/);
    assert.match(screencast, /isBlockedJailChord/);
    assert.match(ui, /isSeatEscapeChord/);
    assert.match(readme, /cannot open another Chrome tab/i);
    assert.match(zh, /不能再开 Chrome 标签/);
    const wm = readFileSync(resolve(root, "docker/update-autostart.sh"), "utf8");
    assert.match(wm, /gpc-jail-keys/);
    assert.match(wm, /C-T/);
    assert.match(wm, /F12/);
    assert.match(gw, /createParkedChatGPTTab/);
    assert.match(readme, /keeps each member in their own project/i);
    assert.match(readme, /in-page lock/);
    assert.match(readme, /g\/g-p-/);
    assert.doesNotMatch(readme, /completely impossible/i);
    assert.match(zh, /留在自己的项目/);
    assert.match(zh, /页面体验锁定/);
    assert.doesNotMatch(zh, /完全不可能/);
    const autostart = readFileSync(resolve(root, "docker/autostart"), "utf8");
    assert.doesNotMatch(autostart, /chatgpt-project-jail|load-extension=.*project/i);
  });

  it("locks 多人分屏 off for this release", () => {
    const gw = readFileSync(resolve(root, "gateway/server.mjs"), "utf8");
    const ui = readFileSync(resolve(root, "gateway/web/app.js"), "utf8");
    const userStore = readFileSync(resolve(root, "lib/users.mjs"), "utf8");
    const deskCdpOnFn = userStore.slice(userStore.indexOf("deskCdpOn("), userStore.indexOf("setDeskCdp"));
    assert.match(deskCdpOnFn, /return false/);
    assert.doesNotMatch(deskCdpOnFn, /data\.deskCdp|process\.env/);
    assert.match(userStore, /if \(on\) throw new Error\("多人分屏暂未开放"\)/);
    assert.match(gw, /if \(body && "cdp" in body && body\.cdp\) return json\(res, 400, \{ error: "多人分屏暂未开放" \}\)/);
    const openStart = gw.indexOf("const open = url.pathname.match(/^\\/api\\/desks\\/([a-z0-9-]+)\\/open$/)");
    const openBlock = gw.slice(openStart, gw.indexOf("const paste = url.pathname.match"));
    assert.match(openBlock, /if \(cdp && projectUrl\) armSeatProjectJail/);
    assert.match(openBlock, /if \(cdp\) kickOnboard/);
    assert.match(openBlock, /watchExclusiveFileChooser/);
    assert.match(openBlock, /seat\?\.mode === "vnc"/);
    const settingsStart = ui.indexOf("function renderSettings");
    const settingsBlock = ui.slice(settingsStart, ui.indexOf("const isMac", settingsStart));
    assert.doesNotMatch(settingsBlock, /多人分屏|暂未开放/);
    assert.doesNotMatch(settingsBlock, /data-cdp-toggle|checkbox|type="checkbox"/);
    const uiDeskCdp = ui.slice(ui.indexOf("function deskCdpOn"), ui.indexOf("function route"));
    assert.match(uiDeskCdp, /return false/);
    assert.match(ui, /if \(deskCdpOn\(state\.deskId\)\) ensureWorkspace\(\)/);
    assert.doesNotMatch(ui, /data-cdp-toggle/);
  });
});
